name: Release builder

on:
  push:
      tags:
      - "deploy/v*"

jobs:
  release:
    runs-on: windows-latest

    env:
      SigningCertificate: Resuscitate_TemporaryKey.pfx
      Solution_Path: Resuscitate.sln
      UWP_Project_Path: Resuscitate\Resuscitate.csproj
      UWP_Project_Directory: .\

    steps:

    - name: Configure Pagefile
      uses: al-cheb/configure-pagefile-action@v1.2
      with:
        minimum-size: 32GB
        maximum-size: 32GB
        disk-root: "C:"

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.0
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        
    - name: Decode the Pfx
      run: |
        $pfx_cert_byte = [System.Convert]::FromBase64String("MIIKSgIBAzCCCgYGCSqGSIb3DQEHAaCCCfcEggnzMIIJ7zCCBgAGCSqGSIb3DQEHAaCCBfEEggXtMIIF6TCCBeUGCyqGSIb3DQEMCgECoIIE/jCCBPowHAYKKoZIhvcNAQwBAzAOBAhkWJHjovTKkAICB9AEggTYXiwQcLHbm+Mh0/5QYLxe9TPG3UC0SU9P/2+Cwg9Ztvbiew9Wj8uBJsqiBCQ9UndbohvUcqQKV0IV/JnPrb5Kq+H6m4tXDLrp4C9iZIwUzeZnarw554QE42jnyd2WB8SIDGgL2PEqauMSMEQyRQ37l/p6pXL4S+nuQfq/7l616dGBGXMnV1CnHPEobNOZInnxAFLaFHmZ1l44X1x8rwICrXLy8ornGcjsvSNnIMuOM6iIfyP2EwgWKVNvkrSWUqWrVt4nAB1wXAQ0I3X/9ec4HS6RDojMucCrKQBQsGgs9dB2wPfpUew3fmZvxBzUBNoI3yPcgMHkPOdlcqFV6tSKDshVYfP2K22qXmMFNnhWUF1bnhSOaoGm0ViXoRtxXLqy5RYLyxJwLqeEmcdu4qhwxSgk9QgikGLhH4RhUeb05deJ0SgKy3dbIBMJCsLg08qrvwI5wQMcVz+gHCE7x94/sJuAcbmRQGfTtH/TvkrJImTESxfPgcaUgFy3g9WJsNaDtPP31Z+Ij0tyiBgmv+qWka5ho7jKrJESDiu3LIsp17eqhMVbWBhvyMylx+Dm3trbmcb37CX1xilbisoKc15tkJBV/KYT0UpB+Apc5nQN5PY2+MHEuJ0xIcR3phCX1JNhM8iWYiZxGnAwcszuBEuGRb2+tVARw6j85iccXWdQfXLumY1iPl2BAVZSew75cLRW3dvoBNG29W4Sme9c4go9RTLwpMXnDcCQ89kRLv+tlV2A5GIe/sl796FDLWB+pb0evijSSrfpWtlRM0Lj2bV4+KlYXd37WHAAK+CWdw6AKlZsx9QNamqqUncbE4liygWxzNOgcVZhpAQ3Gir3zb+r2by/3GYe+ipKpcDLHj4dzeq9DX7fOxm3hRMPMEZVXEmxktr68KzwUtZXNdjZzG+1/a8XlVcnp1XfD6+1Mi8sD5XD80OTOJd0u5yT7+K6BNru0A3+GI73XiVXN/vLlLX4F0bVflrCG6XFyDc9hY8/P+cPMU8CFaYVwTk+QiO1YBimqSQ7oCnsKU396AjvVLNgPnrZWm9UYgN6i1Y05ldfqCReswsrkiTojzAKC7E/tvx2e7QrFpVSRcl01b0iX/2oY91DQh0XYFWgj8OAb+FJPdmhdbm7nkGvgf+1ceJvJhGdMse6RoAEbIVSKjptW/8rlLUD99JMj1KijhrEsgUQl+NMTfeTObqCS8kFJrHI0jCNQpmdXwo1+oHnMN5f2+EL6vJF0TRl4r/ztmKZylDOJTzb/ySXuopdF6rWfyCLhLYgGBly2dCjSHnYLwW8gX65NPg1WSlVT3sfU2NyunP5q3TrOkSV87b52esxqAbLHFqkb4PjGxmbeoRCDdkVrOGKKwzbECpRRP/owrmm8jk3D8ryWicQtD0MxjhMR8cQFf/dhQY4L7LbA23THQb/JrlRwWMHvvUHWoGuDHeJU+BhiVOh2rDWkMS912jAlD+947OoFWQ2EMzootHB5ap0Y7Y6wxbS0dWmpFvuL8E85xkA8WOiE50tbbyYtZ0F2FPzO7/CorOfufbTtsBL8iJBUVe/FVVD4xCP7ogvTRJAHWr4RCAvAHt4sz1gZvmCDwkg8ylrpkqwH/GPGBCuoLhS8jmDGkh44+0hM5us4L4slMsuc7zXYNo1Jr1RsDGB0zATBgkqhkiG9w0BCRUxBgQEAQAAADBdBgkqhkiG9w0BCRQxUB5OAHQAZQAtAGIAZAAzAGYAZAAxADAAZQAtADkAYQA2ADkALQA0ADUAMwBlAC0AOQAxADgANAAtADUAMwAzAGEANgBlADIAMwBjADUAMQBjMF0GCSsGAQQBgjcRATFQHk4ATQBpAGMAcgBvAHMAbwBmAHQAIABTAG8AZgB0AHcAYQByAGUAIABLAGUAeQAgAFMAdABvAHIAYQBnAGUAIABQAHIAbwB2AGkAZABlAHIwggPnBgkqhkiG9w0BBwagggPYMIID1AIBADCCA80GCSqGSIb3DQEHATAcBgoqhkiG9w0BDAEDMA4ECPc3KvKcKEWbAgIH0ICCA6DvgKlqjYv+xJ/z8taVahLy8AAbOg8wdijuLEXxi7YKO6Kcb2rIimzHL5jUfZaLfMNnfvONM7Q6Fz58vdxojoJAAaT7U+VUzYw8gHW6jta/B8sGcqbMDszfKrkq1k9nimWRrGZPN/2RT0yGrjy3pv3Pc98DdtojS2JiwoCxMU3dOt76IsaGnuqibugV5N1aJtgdL9aK5PRL+Q3K+IF+QZC7Be5fxbp20x/jvqStv54wwx7ztC/xKt41fc03YRZrIyLeUKyK8bL2+kytfPKs40CUUXTGDr1bkgIzUJR93a07rRFH+YwM9Bv7eKaEvi8oAiP7MPkkCYjUhd8iDq+dg7ka4qt/kfefQtAeVdc9djqEnsTUXE8OECHniMatpY6GrlALVaMu69kXJlOhlqB4o7KuxC5QpQf/0RgOgJVtlBJunb0SikIXk71prQyZlGNW2TfbUGJvEoCoJKfB8iV1GLFAoMQYycpzomtSxD3Vgl9kc82uPjbKz+5sJ66JzAZMHxoex3t2h7dzd4xPcErox5kRMLOMUDa481KyhxPQKbbdIyXaJTs6BxYI8094826OUM4o8ynj8iuzkqGhoT4cDD5su0ltGwqHF9ULHlvz6Kk2FX0nxufTT4TtNcwqmVg7rNNhVo2JmlA6c5tOzltvokpwwExCRnOdHxOZESB8EyXI4an+2lFqnDOShe6VoPmu1F4or7ABFnp+9IEPF2zwj/S8xc9/yH81sbFqxUywc6LkuSbtEHzJNLtl7HPmYx16+fMSsLoQOPcx70t30ey3/1aNcCZQukaXgTXNpEMmJawrlSRNmEes4rY9uMWs7RnNmxHn9VFWh15wxYMXKpvD6bQzWkTdkInapcP91G7gcI4rGiaxaTa2LjVzu8BlWKK0AHRQtH0lwcqmz5wxcOgywaT2PigTNtahsSv4ysFsz+6Z96HKNr41dSvK9wb+tums6rP/AJT6PJ4Xj3Yi0Whe4wMXDcXr5JPH29b2b79XuAV03iat5/FE0ijsYUMM7NCRfQxnmwyTPGJnQ88WP9a8tKCFtv0JJP/3UpceMJCimoEnxPBRNV5AbfQQB9WvuKUf480PDYk3iMg6iSaChr3n5gOcijOvsdIg7vaHvENgrR2j/2PeIMpLMs6bSrb/F5cKjmAUbdX2tFuoaBqo3nNv7hMRd3mJ9uIp4Zs56khSoLaJm1DqN1bCUtyYJa+91yUkGnyKHLjr6z1/Ha5nTxNv21tsMDswHzAHBgUrDgMCGgQUyufbGD6icR0zwiGQybq8fRkbG6IEFI+joMUmN/dv2hqweQqNkarxQwUbAgIH0A==")
        $currentDirectory = Get-Location
        $certificatePath = Join-Path -Path $currentDirectory -ChildPath $env:UWP_Project_Directory -AdditionalChildPath $env:SigningCertificate
        [IO.File]::WriteAllBytes("$certificatePath", $pfx_cert_byte)
        
    - name: Build the sideload solution
      run: msbuild $env:Solution_Path /p:Platform=x86 /p:AppxBundle=$env:AppxBundle /p:AppxBundlePlatforms="x86|x64" /p:AppxPackageDir=C:\DeployOutput /p:AppxPackageSigningEnabled=true /p:PackageCertificateThumbprint="" /p:PackageCertificateKeyFile=$env:SigningCertificate /p:PackageCertificatePassword="password" /restore
      env:
        AppxBundle: Always
        BuildMode: StoreUpload
        Configuration: Release
   
    - name: Create archive
      run: Compress-Archive -Path C:\DeployOutput\* -DestinationPath C:\DeployOutput\Resuscitate.zip

    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Rescuscitate ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Update release asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: C:\DeployOutput\Resuscitate.zip
        asset_name: Resuscitate.zip
        asset_content_type: application/zip
