name: Testing
on: [push]
env:
    ACTIONS_ALLOW_UNSECURE_COMMANDS: true
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master

    - name: Setup csc.exe
      uses: yoavain/Setup-CSC@v5

    - run: csc test.cs
    - run: .\test.exe